<?php
/**
 * @author JKetelaar
 */

namespace SaasFeeBundle\Repository;

/**
 * LineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineRepository extends \Doctrine\ORM\EntityRepository
{
}
