<?php

namespace SaasFeeBundle\Repository;

/**
 * LineStopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineStopRepository extends \Doctrine\ORM\EntityRepository
{
}
